### PR TITLE
docs(rfc): Optimus Dashboarding

### PR DESCRIPTION
**Pull request by Mryashbhardwaj**

### CODE REVIEW

**Review by sravankorumilli — COMMENTED** [review]
@Mryashbhardwaj can we update the RFC with all the details as per our last discussion.

**Comment by sravankorumilli** [comment]
@Mryashbhardwaj can we update the rfc and then we can merge the same.

**Comment by ravisuhag** [comment]
@sravankorumilli @Mryashbhardwaj can this be merged?

**Comment by Mryashbhardwaj** [comment]
@ravisuhag 

yes merging this

**Pull request merged**
